Updating Readme file for the QA tested scenarios. Added ARIA, SEED and SHA224 enums.
fortanix/sdkms-client-go pull request #9
Opened 2023-05-12 04:52 UTC by captain-rohit

2023-05-12 16:48 UTC, mzohreva requested changes

2023-05-12 16:48 UTC, mzohreva commented on examples/crypto_ops/main.go
> +	myAPIKey      string = "NzI0OGM3MjgtNDA2Yy00MDkxLTk1NWMtNjE5ZDYwMDY1NTFhOmpNZmU2LW9xWjlMdEVIQ0lLQTg2UnUxWHJ4dXVEWWw4MjRBQlFpRmpyR01OS3pwSDdTTEF6RUZfb25kZVk5enJOQkhhNi1ETTktaUlfTHlpc1FMZkpn"
Please don't put secrets in a public repository

2023-05-12 16:48 UTC, mzohreva commented on README.md
> +## Following are the scenarios tested
This is not the right place to put this information.

2023-05-15 05:56 UTC, govardhanfortanix approved these changes

2023-05-15 07:02 UTC, captain-rohit commented on README.md
> +## Following are the scenarios tested
@mzohreva removed it.

2023-05-15 07:19 UTC, captain-rohit commented
bors r+

2023-05-15 07:24 UTC, merged